### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by jaakkor2** [SimonDanisch/ClipperBuilder#2]
Minor confusion about versions.  Is it v1.0.0 like the tag says, or v6.4.0 like it says here
https://github.com/SimonDanisch/ClipperBuilder/blob/v1.0.0/clipper.hpp#L4
or v6.2.6
https://github.com/SimonDanisch/ClipperBuilder/blob/v1.0.0/clipper.hpp#L37

BTW, last official seems to be v6.4.2.
https://sourceforge.net/projects/polyclipping/files/clipper_ver6.4.2.zip/download

Could the Julia ClipperBuild version somehow reflect the Clipper version?

**Comment by SimonDanisch** [comment]
Sounds good, didn't realize they have proper versioning

**Comment by jaakkor2** [comment]
Closing the issue, addressed by https://github.com/JuliaPackaging/Yggdrasil/pull/712.
